---
- name: open network port
  firewalld:
    service: "{{ network_port }}"
    permanent: yes
    state: enabled
    immediate: yes

- name: start service httpd
  service:
    name: "{{ service_name }}"
    state: started
    enabled: yes

- name: restart service httpd
  service:
    name: "{{ service_name }}"
    state: restarted
